# Site settings
title: Sameer Mene
description: All about me!
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.sameermene.com" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Sameer Mene
user_description: >-
  A Cloud Architect and "Kubestronaut", based in Pune India, with more than 14 years of experience,
  I specialize in cloud technologies, particularly Kubernetes and AWS, 
  while also being proficient in Java, Go, and Python programming 
  languages. With a solid background in the telecom domain and a keen 
  interest in emerging technologies such as 5G, my expertise extends 
  to the realms of AI, LLM, and the dynamic landscape 
  of Web 3.0. Committed to pushing the boundaries of innovation, 
  I am dedicated to crafting robust solutions that leverage 
  cutting-edge advancements to drive digital transformation and shape 
  the future of technology.
user_title: Cloud Architect
email: samene@gmail.com
# twitter_username: lorem_ipsum
instagram_username: smene_in1
facebook_username: samene
linkedin_username: samene
github_username:  samene
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

